### ISSUE TITLE
Feature Request: Persian language support

### ISSUE THREAD

**Issue by Ceyed** [mhvn092/nvim#2]
Can we have Persian language support?

![image](https://github.com/mhvn092/nvim/assets/61240869/5108a704-a6b7-4756-93a2-ca2de2d4b56b)

**Comment by mhvn092** [comment]
in cmd write the following:
:set termbidi
:set arabic

**Comment by mhvn092** [comment]
if you need more options look at this :
[:help arabic.txt](https://neovim.io/doc/user/arabic.html)
